name: Validate Pipelines

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
      - uses: google-github-actions/setup-gcloud@v1
      - run: gcloud components update --quiet
      - run: gcloud components install beta --quiet
      - uses: astral-sh/setup-uv@v7
      - run: gcloud beta orchestration-pipelines validate --pipeline-paths=mnjbujhvhv.yaml --environment=hhhhh --quiet
