environments:
  hhhhh:
    project: "noble-beanbag-497411-m4"

    region: "us-west2"

    # TODO: Replace with your Composer environment
    composer_environment: "YOUR_COMPOSER"

    # TODO: Replace with your artifacts bucket
    artifact_storage:
      bucket: "YOUR_BUCKET"
      path_prefix: pipelines

    variables:
      # TODO: Replace with your service account
      service_account: "YOUR_SERVICE_ACCOUNT"
      network_uri: projects/noble-beanbag-497411-m4/global/networks/default

    pipelines:
      - source: mnjbujhvhv.yaml
