import os
import requests
import glob

# Files generated by OpenCode Copilot
DOCS_DIR = r"C:\Users\HP\OneDrive\Documents"
API_URL = "http://127.0.0.1:8000/api/sync_code"

# Files to sync based on listing
files_to_sync = [
    "pipeline.py",
    "query.html",
    "rico_cross_reference.py",
    "bq_rico_matches.csv",
    "HB_OutOfState_LLCs.csv",
    "HB_Suspicious_LLC_Matrix.csv",
    "rico_evidence_matrix.csv"
]

print("Syncing Copilot files to Central Vault...")

for filename in files_to_sync:
    path = os.path.join(DOCS_DIR, filename)
    if os.path.exists(path):
        try:
            with open(path, "r", encoding="utf-8") as f:
                content = f.read()
            
            ext = filename.split('.')[-1]
            language = ext if ext in ['py', 'html', 'csv'] else 'text'
            
            payload = {
                "filename": filename,
                "code_content": content,
                "language": language,
                "description": f"Automated sync of Copilot artifact from Documents folder."
            }
            
            res = requests.post(API_URL, json=payload)
            if res.status_code == 200:
                print(f"Success: Synced {filename}")
            else:
                print(f"Failed {filename}: {res.text}")
        except Exception as e:
            # Maybe it's a binary file or encoding issue (like large CSVs)
            print(f"Error reading {filename}: {e}")
    else:
        print(f"Not found: {filename}")

print("\nSync Complete!")
