post_onboarding:  {
  completed_steps:  POST_ONBOARDING_STEP_TYPE_MANAGER_WELCOME
  completed_steps:  POST_ONBOARDING_STEP_TYPE_USAGE_MODE
  completed_steps:  POST_ONBOARDING_STEP_TYPE_AGENT_CONFIGURATION
  completed_steps:  POST_ONBOARDING_STEP_TYPE_ADD_WORKSPACE
}
seen_nuxs:  {
  uids:  27
  uids:  26
  uids:  24
  uids:  23
  uids:  25
  uids:  29
}
agent_onboarding_completed:  AGENT_ONBOARDING_STATE_COMPLETED
last_selected_agent_model:  MODEL_OPENAI_GPT_OSS_120B_MEDIUM
migrate_convos_into_projects:  MIGRATION_STATUS_COMPLETED
installation_uuid:  "894df2e2-9093-42ce-bac9-f3f54860728d"
migrate_retroactive_projects:  RETROACTIVE_MIGRATION_STATUS_COMPLETED_UNNECESSARY
